/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => SmaugPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var import_child_process = require("child_process");
var DEFAULT_SETTINGS = {
  smaugDirectory: ""
};
var SmaugPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("dragon", "Run Smaug Archiver", (evt) => {
      this.runSmaugJob();
    });
    this.addCommand({
      id: "run-smaug",
      name: "Run Smaug Bookmark Archiver",
      callback: () => {
        this.runSmaugJob();
      }
    });
    this.addSettingTab(new SmaugSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  runSmaugJob() {
    if (!this.settings.smaugDirectory) {
      new import_obsidian.Notice("Smaug: Please configure the Smaug project directory in settings first.");
      return;
    }
    new import_obsidian.Notice("\u{1F409} Smaug is waking up... processing bookmarks...");
    const command = `npx smaug run`;
    (0, import_child_process.exec)(command, { cwd: this.settings.smaugDirectory }, (error, stdout, stderr) => {
      if (error) {
        console.error(`Smaug execution error: ${error.message}`);
        new import_obsidian.Notice("\u274C Smaug failed! Check developer console for details.");
        return;
      }
      if (stderr) {
        console.warn(`Smaug stderr: ${stderr}`);
      }
      console.log(`Smaug output: ${stdout}`);
      if (stdout.includes("No bookmarks to process")) {
        new import_obsidian.Notice("\u{1F409} Smaug: No new bookmarks to hoard.");
      } else {
        new import_obsidian.Notice("\u{1F409} Smaug finished hoarding! New bookmarks archived.");
      }
    });
  }
};
var SmaugSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Smaug Archiver Settings" });
    new import_obsidian.Setting(containerEl).setName("Smaug Project Directory").setDesc("Absolute path to where you cloned the smaug-obsidian repository (e.g. /Users/mayanklavania/moonshot_projects/smaug-obsidian)").addText((text) => text.setPlaceholder("Enter directory").setValue(this.plugin.settings.smaugDirectory).onChange(async (value) => {
      this.plugin.settings.smaugDirectory = value;
      await this.plugin.saveSettings();
    }));
  }
};
